Change Draco modules to be created asynchronously
visgl/loaders.gl pull request #1002
Opened 2020-10-30 18:43 UTC by FrankGalligan

In general Draco npm modules have always been created asynchronously.

We are planning to release Draco 1.4.0, which uses a new version of emscripten and causes applications to fail more often if they were getting created synchronously as the timing has changed.

Will this change work in your code?

2020-11-10 18:59 UTC, belom88 requested changes
Tests hang up on this branch.
@FrankGalligan , notice that loaders now handle 1.3.6 draco version (see https://github.com/visgl/loaders.gl/blob/f1c89f1907c474436275ae8fd451d1fb315814b7/modules/draco/package.json#L44)
Should 1.3.6 handle your changes? If not - we need to update loaders to 1.4.0 first.

2020-11-12 17:29 UTC, FrankGalligan commented
I think so but I wasn't sure how to check in this project.

2020-11-13 00:28 UTC, ibgreen commented
Just testedm this seems to run fine on Node.js and on browser main thread.

But the `DracoWorkerLoader` hangs. I did rebuild it using `yarn bootstrap` before testing. 

@FrankGalligan not sure if that is a clue, if any consideration using this callback mode on a worker thread?

<img width="531" alt="Screen Shot 2020-11-12 at 4 23 53 PM" src="https://user-images.githubusercontent.com/7025232/99012612-a77c4180-2503-11eb-9f10-d15c04938514.png">

2020-12-09 13:58 UTC, belom88 commented
@FrankGalligan . Thank you for this PR. We used you approach in https://github.com/visgl/loaders.gl/pull/1029 . This PR can be closed

2020-12-09 14:56 UTC, closed without merging