Remove segmentation data property from i3s example
visgl/loaders.gl pull request #1505
Opened 2021-06-15 14:14 UTC by dryabinin-actionengine

2021-06-15 16:08 UTC, ibgreen approved these changes

2021-06-16 06:01 UTC, belom88 requested changes
Looks like wrong conflict resolving. `tile-lalyer.js` has to be deleted.

2021-06-16 06:01 UTC, belom88 commented on examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
> +import GL from '@luma.gl/constants';
This file should be removed

2021-06-16 06:08 UTC, dryabinin-actionengine commented on examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
> +import GL from '@luma.gl/constants';
Yes sure. Already removed.

2021-06-18 11:04 UTC, merged