chore(I3S & I3SDebug): UI improvements
visgl/loaders.gl pull request #1704
Opened 2021-07-26 14:24 UTC by morphoix

![debug-panel](https://user-images.githubusercontent.com/53499331/127005114-658014c5-e792-419f-9541-6a9e5d64cb73.png)
![debug-dark](https://user-images.githubusercontent.com/53499331/127005176-816c3266-f290-465c-801c-6cd16c9c1a80.png)

2021-07-26 14:36 UTC, ibgreen approved these changes
Very cool sci-fi look!

2021-07-26 16:21 UTC, belom88 requested changes

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/components/debug-panel.js
> +  position: sticky;
`sticky` is not supported in IE

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/components/debug-panel.js
> +export const Label = styled.label`
Why `export`?

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/components/memory-stats.js
> +  border: 2px solid #212529;
Too many `border`

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/app-debug.js
> +    return <StatsWidgetContainer ref={(_) => (this._statsWidgetContainer = _)} />;
Remove `const STATS_WIDGET_STYLE = {`

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/app-debug.js
> +    const {selectedMapStyle, tileInfo, debugOptions, showMemory} = this.state;
init `showMemory` in constructor

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/app-debug.js
> +          {showMemory ? `Hide ` : `Show `}Memory Usage
```suggestion
          {showMemory ? `Hide` : `Show`} Memory Usage
```

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/app.js
> +    const {viewState, selectedMapStyle, selectedFeatureAttributes, showMemory} = this.state;
init `showMemory` in constructor

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/app.js
> +        <MemoryButton onClick={() => this.setState({showMemory: !showMemory})}>{showMemory ? `Hide ` : `Show `}Memory Usage</MemoryButton>
Ditto

2021-07-26 16:21 UTC, belom88 commented on examples/website/i3s/components/control-panel.js
> +  background: transparent;
Too many `background`

2021-07-27 09:49 UTC, morphoix commented on examples/website/i3s/components/debug-panel.js
> +  background: rgba( 36, 39, 48, 0.7);
the rule opacity will make the whole element transparent but I need only background to be transparent

2021-07-27 10:15 UTC, morphoix commented on examples/website/i3s/components/control-panel.js
> +    color: rgb(36,39,48);
> convert to HEX to have all colors in the same notation

fixed everywhere except cases with alpha-channel

2021-07-28 08:51 UTC, belom88 requested changes
"Show more/less info" animation doesn't look correct;
"Statistics" overlaps "Debug Panel". We need to be able to use these panels simultaneously
"Clear all" look different in Firefox;
Select options look different in Firefox;

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/debug-panel.js
> +      color: isClearButtonDisabled ? '#f2e9e4' : 'rgb(36,39,48)',
use HEX, please

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/memory-stats.js
> +`;
New line in the end of the file

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/tile-validator.js
> +  background: gba( 0,0,0,.5);
`rgba`?

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/control-panel.js
> +  transition: all 1s ease;
Not fixed

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/semantic-validator.js
> +        <td style={{padding: '3px', color: 'rgb(0, 173, 230)'}}>{index + 1}</td>
Use HEX

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/semantic-validator.js
> +        <td style={{padding: '3px', color: 'rgb(242, 233, 228)'}}>{WARNING_TYPES[warning.type]}</td>
Use HEX

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/toggle-switch.js
> +  display: inline-block;
`display: inline-block` and `position: absolute` simultaneously doesn't have sense.

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/toggle-switch.js
> +  -webkit-transition: 0.4s;
if you want to use browser-specific extensions for `transition`, use it everywhere in your code.

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/toggle-switch.js
> +    box-shadow: rgb(0 0 0 / 40%) 0px 2px 4px 0px;
Don't see effect of this rule on the screen

2021-07-28 08:51 UTC, belom88 commented on examples/website/i3s/components/toggle-switch.js
> +    -webkit-transition: 0.4s;
Ditto

2021-07-28 10:52 UTC, morphoix commented on examples/website/i3s/components/debug-panel.js
> +  text-shadow: 1px 1px 1px #212529;
> Don't see effect of this line

the text-shadow is for light map

2021-07-28 11:48 UTC, belom88 approved these changes

2021-07-28 11:49 UTC, merged