chore(wkt): improved wkt typings
visgl/loaders.gl pull request #1706
Opened 2021-07-26 14:54 UTC by Evin-K

2021-07-26 15:21 UTC, belom88 requested changes
`modules/wkt/src/workers/wkt-worker.js → modules/wkt/src/workers/wkt-worker.ts` - edit scripts in `package.json`

2021-07-26 15:21 UTC, belom88 commented on modules/wkt/src/lib/parse-wkt.ts
> +    var rings = Array();
What advantage of this way of array initialization?

2021-07-26 15:21 UTC, belom88 commented on modules/wkt/src/lib/parse-wkt.ts
> +    var rings = Array();
I suggest replacing all `var` declarations with `const` of `let` int this file.

2021-07-26 15:24 UTC, ibgreen commented
I just landed https://github.com/visgl/loaders.gl/pull/1705 which touched the WKB parts but not the WKT parts.

Just rebase and focus on the WKT improvements.

2021-07-27 09:19 UTC, belom88 approved these changes

2021-07-27 12:57 UTC, dryabinin-actionengine requested changes

2021-07-27 12:57 UTC, dryabinin-actionengine commented on modules/wkt/src/lib/encode-wkt.ts
> +}) {
I think the return value can be added right after arguments list:
```
export default function encodeWKT(gj: {
  type: string;
  properties?: {};
  geometry?: any;
  coordinates?: any;
  geometries?: any;
}): string
```

2021-07-27 12:57 UTC, dryabinin-actionengine commented on modules/wkt/src/lib/encode-wkt.ts
> +}) {
Also should we avoid `any` type in `encodeWKT` function arguments?
Can we just be more accurate with typings here?

2021-07-27 12:57 UTC, dryabinin-actionengine commented on modules/wkt/src/lib/encode-wkt.ts
> +  function pairWKT(c: any[]) {
Should we detect what particular type here?
Do they always have different types?

2021-07-27 13:04 UTC, ibgreen approved these changes
This looks like a solid improvement. Agree it would  be ideal to replace all occurrences of `any`. This could also be done a second PR.

2021-07-27 13:04 UTC, ibgreen commented on modules/wkt/src/lib/encode-wkt.ts
> + * @param gj
Nit: I don't like abbreviations, type out as `geojson`...

2021-07-30 16:12 UTC, dryabinin-actionengine approved these changes

2021-07-30 16:28 UTC, ibgreen approved these changes

2021-07-30 16:28 UTC, ibgreen commented on modules/wkt/src/lib/encode-wkt.ts
> +      return 'POINT (' + pairWKT(gj.coordinates as any[]) + ')';
Can we do a follow up PR where we remove this `any`?

2021-07-30 16:28 UTC, merged