chore(I3S-Debug): memory stats positioning change
visgl/loaders.gl pull request #1725
Opened 2021-07-30 02:04 UTC by morphoix

![13](https://user-images.githubusercontent.com/53499331/127588691-58c7bbb2-50dc-4546-bd7f-60107accb7e8.png)
![12](https://user-images.githubusercontent.com/53499331/127588701-2f6e5fb4-5ca4-4c64-baeb-868031ed4bbb.png)
![11](https://user-images.githubusercontent.com/53499331/127588703-489314bf-dbaa-42eb-b3cf-1e304825cd0b.png)

2021-07-30 02:56 UTC, ibgreen approved these changes
UI is starting to look very polished. 

Note that there is a bug in the memory stats formatting. Probably in probe.gl. Would be great to fix that.

I think the labels could also be improved. Try showing them to someone that doesn't know what the app does...

Maybe something like:
- "Show" -> "Minimap"
- "Use Different Viewports" -> ??? What does this do?
- "Pickable" -> What is the point of letting user disable picking? Switching between object and tile picking could have made more sense? I forgot why this switch is here.
- "UV DEBUG TEXTURE" -> "TEXTURE UVs"
- "WIREFRAME MODE" -> "WIREFRAME"
- "BOUNDING VOLUMES" -> None/Sphere/Box

2021-07-30 10:34 UTC, belom88 commented
>"Use Different Viewports" -> ??? What does this do?

* The mini-map loads tiles from its viewport state with this option, instead of showing tiles of the main viewport
* For showing main viewport tiles `Scatterplot` is shown on the mini-map

>"Pickable" -> What is the point of letting user disable picking?

* Tiles are highlighted onHover. It's looks to noisy when picking is continually switched on.
* Switching between object and tile picking make sense. We didn't have time to do it during the contract. It requires extra efforts.

2021-07-30 14:32 UTC, morphoix commented
> * "Show" -> "Minimap"
> * "Use Different Viewports" -> ??? What does this do?
> * "Pickable" -> What is the point of letting user disable picking? Switching between object and tile picking could have made more sense? I forgot why this switch is here.
> * "UV DEBUG TEXTURE" -> "TEXTURE UVs"
> * "WIREFRAME MODE" -> "WIREFRAME"
> * "BOUNDING VOLUMES" -> None/Sphere/Box

@ibgreen As bounding volumes have also select by color my suggestion is to leave the toggle but remove both of selects from a screen when it's not used

![Screenshot from 2021-07-30 17-24-26](https://user-images.githubusercontent.com/53499331/127667649-9f680729-868f-42c1-ad93-2e08ccc8500f.png)
![Screenshot from 2021-07-30 17-09-11](https://user-images.githubusercontent.com/53499331/127667653-cb245b82-73ca-427d-89ee-bdcff935a1ef.png)
![Screenshot from 2021-07-30 17-04-04](https://user-images.githubusercontent.com/53499331/127667654-7d0fa525-8b71-49e1-8214-e22ecfeca346.png)

2021-07-30 14:44 UTC, belom88 requested changes
@ibgreen  do we need the website supported on IE11?

2021-07-30 14:44 UTC, belom88 commented on examples/website/i3s/components/control-panel.js
> +  grid-template-columns: 100px 100px 100px;
grid isn't supported by IE

2021-07-30 14:57 UTC, dryabinin-actionengine commented
@morphoix Also debug texture picture should be larger in debug panel. User should be able to compare picture with debug texture on the tileset.

2021-07-30 15:11 UTC, morphoix commented
> @morphoix Also debug texture picture should be larger in debug panel. User should be able to compare picture with debug texture on the tileset.

hover effect added

2021-08-02 10:47 UTC, belom88 approved these changes

2021-08-02 10:47 UTC, belom88 commented on examples/website/i3s/app.js
> +
Nit: remove empty line

2021-08-02 10:47 UTC, belom88 commented on examples/website/i3s/components/debug-panel.js
> +
Nit: remove empty line

2021-08-02 13:27 UTC, merged