chore(mvt) improved types in mvt module
visgl/loaders.gl pull request #1727
Opened 2021-07-30 09:37 UTC by Evin-K

2021-07-30 12:24 UTC, belom88 requested changes
I suggest define types instead using `any`. You can use tests debug to observe structure of objects.

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.ts
> +    options: {x: number; y: number; z: number} | ((data: any[], feature: {extent: any}) => void)
Interestingly, can we overload this method for two different types?

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.ts
> +    function project(data: any[]) {
Move this function outside of the class. It would be great to create a `helper` file for outer functions.

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.ts
> +  let ringAreas: any[] = [];
![image](https://user-images.githubusercontent.com/18549629/127650255-02be9e9d-3fa0-4407-bdd5-c2bfcf69568b.png)

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-layer.ts
> +  _keys: any[];
`string[]`

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-layer.ts
> +  _values: any[];
`(number | string | boolean | null)[]`

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/binary-vector-tile/vector-tile-layer.ts
> +  _features: any[];
number[]

2021-07-30 12:24 UTC, belom88 commented on modules/mvt/src/lib/parse-mvt.ts
> + * @return {?Object} A GeoJSON geometry object or a binary representation
remove types from comments as you have them in code

2021-08-02 12:07 UTC, ibgreen approved these changes

2021-08-02 12:07 UTC, ibgreen commented on modules/mvt/src/lib/mapbox-vector-tile/vector-tile.ts
>  function readTile(tag: number, layers?: {[x: string]: VectorTileLayer}, pbf?: Protobuf) {
Let's move `void` into the types and remove from JSDoc (in all places!)
```suggestion
 */
function readTile(tag: number, layers?: {[x: string]: VectorTileLayer}, pbf?: Protobuf): void {
```

2021-08-02 12:07 UTC, ibgreen commented on modules/mvt/src/lib/parse-mvt.ts
>  export default function parseMVT(arrayBuffer: ArrayBuffer, options?: LoaderOptions) {
Can we add a return type here?

2021-08-02 12:07 UTC, ibgreen commented on modules/mvt/src/lib/types.ts
> +  numericPropKeys: string[];
Make sure you look at the binary geometry types in `@loaders.gl/schema`. 

Ultimately the idea is that these loaders return data in those standardized types.

2021-08-03 10:24 UTC, belom88 approved these changes

2021-08-06 14:45 UTC, merged