fixed duplicated texture output
visgl/loaders.gl pull request #2048
Opened 2022-01-06 21:36 UTC by Tamrat-B

@belom88 @dryabinin-actionengine Fix for #2047

2022-01-10 07:24 UTC, belom88 requested changes
There should be logic of changing `textureSetDefinitions`

2022-01-10 13:44 UTC, belom88 commented
@Tamrat-B , we will help you to land this PR

2022-01-10 14:31 UTC, ibgreen approved these changes

2022-01-10 17:15 UTC, Tamrat-B commented
> There should be logic of changing `textureSetDefinitions`

I think this particular issue was just a bug - there shouldn't be duplicate textures in the slpk. We should however, have an option with the converter to output only ktx2 as an option (as ktx2 is already a supper set from which both jpg/png & dds could be derived from); there are use cases where we don't want jpeg/png in addition to ktx2. Currently I3S is keeping jpeg to let client applications catch up supporting ktxt2. Once that happens, next version of I3S will drop all legacy texture formats..

2022-01-11 20:02 UTC, belom88 approved these changes

2022-01-11 20:03 UTC, merged