fix(parse-i3s-tile-content): I3S conversion issue without draco
visgl/loaders.gl pull request #2064
Opened 2022-01-20 12:40 UTC by HeimEndyd

An error occurred when a scene with materials without textures was parsed. When trying to get a uv0 buffer, we went beyond the buffer boundary. Parsing 'Geometry buffer' depends on 'ordering'. In one scene some materials may have texture while others may not. Because of this, we cannot guarantee to remove the error by affecting only the 'ordering', removing the uv0 from it. Therefore, we will simply skip the step with getting uv0 if getting it goes beyond the boundaries of the buffer.

spec: https://github.com/Esri/i3s-spec/blob/master/docs/1.8/defaultGeometrySchema.cmn.md

2022-01-20 13:13 UTC, belom88 commented
You still need to remove `uv0` from `defaultGeometrySchema` if there is no any texture in the whole layer. ArcGis won't mind this logic.

2022-01-20 13:14 UTC, belom88 requested changes
You still need to remove uv0 from defaultGeometrySchema if there is no any texture in the whole layer. ArcGis won't mind this logic.

2022-01-24 14:41 UTC, belom88 approved these changes
One nit comment

2022-01-24 14:41 UTC, belom88 commented on modules/tile-converter/src/i3s-converter/i3s-converter.ts
> +      }
```suggestion
      this.layersHasTexture = this.layersHasTexture || resources.texture;
```

2022-01-24 17:16 UTC, ibgreen approved these changes

2022-01-24 17:16 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
> +        break;
Nit: We generally avoid `break` statements. It is OK if you can't find another way.

2022-01-24 17:16 UTC, ibgreen commented on modules/tile-converter/src/i3s-converter/i3s-converter.ts
> +      this.layers0!.store.defaultGeometrySchema.ordering =
No exclamation marks please

2022-01-24 17:16 UTC, ibgreen commented on modules/tile-converter/src/i3s-converter/i3s-converter.ts
> +      this.layersHasTexture = this.layersHasTexture || !!resources.texture;
```suggestion
      this.layersHasTexture = this.layersHasTexture || Boolean(resources.texture);
```

2022-01-25 07:59 UTC, merged