chore(tile-converter): improve tile converter error message
visgl/loaders.gl pull request #2156
Opened 2022-04-22 13:45 UTC by kirillovzah

2022-04-22 14:14 UTC, dryabinin-actionengine commented on modules/tile-converter/src/3d-tiles-converter/3d-tiles-converter.ts
> +    this.message = 'Tile converter does not work in browser, only in node js environment';
I am not sure constructor of  Tiles3DConverter is a good place for such messages. 
I think separate constant will be sufficient.

2022-04-22 15:17 UTC, belom88 requested changes

2022-04-22 15:17 UTC, belom88 commented on modules/tile-converter/src/3d-tiles-converter/3d-tiles-converter.ts
> +const ERROR_MESSAGE = 'Tile converter does not work in browser, only in node js environment';
```suggestion
const ERROR_MESSAGE = 'Tile converter does not work in browser, only in NodeJS environment';
```

2022-04-22 15:17 UTC, belom88 commented on modules/tile-converter/src/3d-tiles-converter/3d-tiles-converter.ts
> +const ERROR_MESSAGE = 'Tile converter does not work in browser, only in node js environment';
Move it to `constants.ts` file in the root of the module. We have the same message in 2 files.

2022-04-22 15:17 UTC, belom88 commented on modules/tile-converter/src/3d-tiles-converter/3d-tiles-converter.ts
> +    if (!isBrowser) {
```
if (isBrowser) {
  console.log(ERROR_MESSAGE);
  return ERROR_MESSAGE;
}

// Put old code here
```

2022-04-22 15:17 UTC, belom88 commented on modules/tile-converter/src/i3s-converter/i3s-converter.ts
> +    if (!isBrowser) {
```
if (isBrowser) {
  console.log(ERROR_MESSAGE);
  return ERROR_MESSAGE;
}

// Put old code here
```

2022-04-22 15:17 UTC, belom88 commented on modules/tile-converter/test/i3s-converter/i3s-converter.spec.js
>  test('tile-converter - Converters#converts 3d-tiles tileset to i3s tileset', async (t) => {
Make a test for Tiles3DConverter (only for browser)

2022-04-25 15:19 UTC, ibgreen approved these changes

2022-04-28 12:49 UTC, belom88 approved these changes

2022-04-28 12:49 UTC, belom88 commented on test/modules.js
> +import '@loaders.gl/tile-converter/test'
```suggestion
import '@loaders.gl/tile-converter/test';
```

2022-04-28 12:54 UTC, belom88 requested changes
Fix conflicts with master. If need help, reach out to me.

2022-04-28 14:54 UTC, belom88 approved these changes

2022-05-04 13:15 UTC, merged