pass i3s loader only required options
visgl/loaders.gl pull request #2188
Opened 2022-06-01 14:32 UTC by kirillovzah

Issue https://github.com/visgl/loaders.gl/issues/1118

2022-06-03 15:44 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
> +function parseHeaders(tileset: I3STilesetOptions, arrayBuffer: ArrayBuffer) {
- If this is now an options object and not a tileset instance, can we call the parameter `options`
- The normal parameter order is `(arrayBuffer, options)`

2022-06-03 15:44 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
> +function parsePositions(attribute: I3SMeshAttribute, tile: I3STileOptions): Matrix4 {
Rename to `options`?

2022-07-04 08:05 UTC, belom88 requested changes

2022-07-12 12:13 UTC, belom88 requested changes

2022-07-12 12:13 UTC, belom88 commented on modules/tiles/src/tileset/tile-3d.ts
> +            content: this.header.content,
remove this too?

2022-07-18 11:27 UTC, belom88 approved these changes

2022-07-25 15:45 UTC, ibgreen reviewed
This changes return value of a lot of functions. But none of these functions have return value types. Please add such types, then I will be comfortable with merging this.

I will say that there was already some subtlety to how this was working as we are passing in a (possibly empty) tile object for these functions to populate and then return that object. Now it is returning something which can be different than the passed in object - so that original choice of passing in an empty object is getting even more confusing. 

Basically we are adding more complexity without addressing the initial complexity making it harder to maintain - but in some sense that is your problem now...

2022-07-25 15:50 UTC, ibgreen approved these changes
After discussion with @belom88 it was explained that `tile` is no longer the full tile but some cherrypicked props to enable worker processing.

My confusion comes from the variable `tile` not being renamed. Please address that in this or a separate PR and I will be OK with this.

2022-07-26 12:15 UTC, merged