fix(3d-tiles): add support for absolute content-uris
visgl/loaders.gl pull request #2211
Opened 2022-07-14 10:15 UTC by usefulthink

Tilesets can use absolute paths or even fully qualified URLs in the
content.uri field. This patch adds support for all of those cases.

How would I best go about testing this? Would it be ok toadd a new Tileset to `test/data/Tilesets` specifically to test the url-handling?

2022-07-14 14:18 UTC, felixpalmer commented on modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts
> +  const rxUrlScheme = /^[a-z][0-9a-z+.-]*:/i;
I would call this variable urlSchemeRegex

2022-07-14 14:22 UTC, felixpalmer requested changes
I agree it would be good to add some tests to verify some common cases. I would recommend adding a new test file to `modules/3d-tiles/test/lib/parsers/` and testing a set of common combinations by importing the `normalizeXXX` functions and testing those in isolation. I think this is clearer and easier to support than adding a full tileset.json

2022-07-15 07:48 UTC, usefulthink commented
Added all the test-cases I could think of for the `normalizeTileData` function. `normalizeImplicitTileHeaders` can't really be tested in isolation since it actually loads the subtree-root and thus requires a working tileset. Those are already tested in `tiles-3d-loader.spec.js`.

2022-07-22 11:38 UTC, felixpalmer approved these changes

2022-07-22 19:13 UTC, merged