chore(i3s): add statistic types
visgl/loaders.gl pull request #2247
Opened 2022-09-05 15:27 UTC by dryabinin-actionengine

2022-09-05 15:30 UTC, belom88 requested changes

2022-09-05 15:30 UTC, belom88 commented on modules/i3s/src/types.ts
> +  mostFrequentValues?: ValueCount;
It should be array

2022-09-05 15:40 UTC, dryabinin-actionengine commented on modules/i3s/src/types.ts
> +  mostFrequentValues?: ValueCount;
FIxed

2022-09-06 08:19 UTC, belom88 approved these changes

2022-09-06 08:22 UTC, merged