Add queryParams option to Tiles3DLoader
visgl/loaders.gl pull request #2252
Opened 2022-09-14 10:22 UTC by felixpalmer

Some tile servers require query parameters to be appended to requests when requesting 3D tiles, a common one being adding an API key. Currently, this is only achievable in deck.gl by using `onTilesetLoad` in a rather hacky way:

```js
new Tile3DLayer({
  id: 'tile-3d-layer',
  data: TILESET_URL,
  onTilesetLoad: tileset3d => {
     tileset3d._queryParams = {key: API_KEY};
  }
});
```

This PR adds an option to `Tiles3DLoader` to support passing the required query parameters directly:

```js
new Tile3DLayer({
  id: 'tile-3d-layer',
  data: TILESET_URL,
  loadOptions: {
    '3d-tiles': {
      queryParams: {key: API_KEY}
    }
  }
});
```

2022-09-14 11:25 UTC, belom88 requested changes

2022-09-14 11:25 UTC, belom88 commented on modules/tiles/test/tileset/tileset-3d.spec.js
> +test.only('Tileset3D#extracts queryParams from loadOptions', async (t) => {
remove `only`

2022-09-14 11:25 UTC, belom88 commented on modules/tiles/src/tileset/tileset-3d.ts
> +    if (this.loadOptions['3d-tiles'] && 'queryParams' in this.loadOptions['3d-tiles']) {
I suggest initializing `3d-tiles` specific data in `_initializeTiles3DTileset` method.

2022-09-14 13:34 UTC, ibgreen commented
I know the 3D tiles team has been proposing a similar PR in the past. 

I have been slow to approve mainly because I would prefer to have a generic solution for query params in loaders.gl core, rather than keep slapping things onto the already exceedingly complex 3d tiles code base. 


Also there has been some work on it here https://github.com/visgl/loaders.gl/pull/807/files I suppose that is more along the lines of preserving params in the URL rather than allowing them to be injected with an additional loader option.

2022-09-14 13:34 UTC, ibgreen commented
We have more multi file loaders and surely the same problem will arise in other placesThough doing it in a general way (top level load option) will of course require more thought.

2022-09-15 08:36 UTC, felixpalmer commented
@ibgreen yes I was a bit surprised that there was no mechanism for dealing with URL params in a general way. Thanks for the pointer to https://github.com/visgl/loaders.gl/pull/807/files. 

One thing that is interesting there is that the query params are being discarded and the `LoaderContext` only has the bare URL. This works for `selectLoaders` etc but when it comes to parsing a tileset, it is no longer possible to pass on the query parameters to the tile requests https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/src/tiles-3d-loader.ts#L49 as the URL has been stripped.

When considering how to deal with query parameters in the API, there is a choice as to whether to include them in the URL, or have them as a separate loader option. From a user's perspective I would argue that there is an expectation that including them in the URL string should work. 

I wonder if a way forward would be to enhance `getResourceUrlAndType` so that it also returned the `queryParams` and then included this on the `LoaderContext`. This way subloaders could access the full URL with the parameters included.

2022-11-09 09:03 UTC, felixpalmer commented
@belom88 @ibgreen could you let me know what you think of the alternative proposal? It would be nice to resolve this one way or another before it gets stale

2023-05-05 00:55 UTC, ibgreen commented
@felixpalmer I made a pass on this, mainly breaking out the queryString processing from the resource-utils. It is ready to land from my point of view. However since we are landing other query string related fixes I will hold off merging for now.

2023-05-05 00:55 UTC, ibgreen approved these changes

2023-05-07 11:59 UTC, merged

2023-05-13 20:57 UTC, jo-chemla commented
Hello there, thanks for that PR, will be very useful! I've tried multiple options to pass url parameters to each tile fetch, with no luck at the moment. Should we pass these url-params 
 - as a queryString or queryParams property, 
 - as a string or object, 
 - and to 3D-tiles or fetch `loaderOptions`? 
 
 Thanks a lot!

Note that in a similar fashion, fetch header passed as a loaderOption is not passed to each tile loading - only to the tileset root fetch request.

Tested on loaders.gl 3.3.5 

```js
const tilesetJson = await load(tilesetUrl, Tiles3DLoader, {
  "3d-tiles": {
    isTileset: true,
    queryParams: { test: 123},
    queryString: "a=123&b=abc",
  },
  fetch: {
    headers: {
      "key": key,
    },
    queryParams: "test=100000000",
    searchparams: "othertest=222222",
  },
```

2023-05-14 10:16 UTC, ibgreen commented
This is a closed PR. discussion moved to https://github.com/visgl/loaders.gl/discussions/2470