fix(i3s-converter): fix default arrays in shared-resources.ts
visgl/loaders.gl pull request #2298
Opened 2022-11-24 19:18 UTC by mspivak-actionengine

According to https://github.com/Esri/i3s-spec/blob/master/docs/1.7/sharedResource.cmn.md
arrays for MaterialDefinitions are expected to have 3 elements (r, g, b).

2022-11-25 08:48 UTC, belom88 requested changes
Add a test reproducing this issue

2022-11-28 14:11 UTC, ibgreen approved these changes

2022-11-28 15:05 UTC, belom88 requested changes

2022-11-28 15:05 UTC, belom88 commented on modules/tile-converter/test/i3s-converter/helpers/shared-resources.spec.js
> +  }
use `deepEqual` to compare objects https://github.com/ljharb/tape#tdeepequalactual-expected-msg

2022-11-28 21:02 UTC, belom88 approved these changes

2022-11-28 21:25 UTC, merged