fix(tile-converter): instant writing in queue
visgl/loaders.gl pull request #2306
Opened 2022-12-16 11:08 UTC by mspivak-actionengine

2022-12-18 10:37 UTC, belom88 requested changes
The PR title will be commit message. Edit title to allign with conventional commit messages: https://www.conventionalcommits.org/en/v1.0.0/
Eg. "fix(tile-converter): instant writing in queue"

2022-12-18 10:37 UTC, belom88 commented on modules/tile-converter/src/lib/utils/write-queue.ts
> +        //   writePromise: writeFileForSlpk(slpkPath, content, `xxx.json`) // INCORRECT !
Move this comment to type definition (9th line)

2022-12-18 20:08 UTC, ibgreen approved these changes

2022-12-19 07:46 UTC, belom88 approved these changes

2022-12-19 07:47 UTC, merged