[chore] implementation of slpk parser
visgl/loaders.gl pull request #2409
Opened 2023-04-11 15:40 UTC by dariaterekhovaae

2023-04-12 09:25 UTC, belom88 requested changes
We cannot use SLPK in I3SLoader at the moment. It is because requests come with url to specific resource inside the layer. So the url will be not be 
`path/to/file.slpk`, it will be, for instance, `path/to/file.slpk/nodes/1/geometry/0`
We cannot split url to SLPK from path inside SLPK. We will think about it later.
What I expect for now is:
* SLPKLoader;
* Input of the loader:
  * `url` (`path/to/file.slpk`);
  * `options.path` (path to the resource inside the SLPK);
  * `options.mode` (`raw`/`http`) - this was discussed with @Tamrat-B . `raw` - `options.path` is path inside the SLPK file, output is ArrayBuffer from the SLPK. `http` - `options.path` is http route compatible with I3S spec (https://github.com/opengeospatial/ogc-i3s-community-standard/blob/main/docs/3Dobject_ReadMe.adoc), output is parsed I3S resource;
* Output: 
  * ArrayBuffer of a resource inside the SLPK;
  * We can parse this resource with I3SLoader.parse function

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +
Why empty line here?

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +class SlpkArchieve {
The class should be in a separate file

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +  /* eslint-disable consistent-return */
I believe you can fix this disable with appropriate types

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +class SlpkArchieve {
Add TSDoc comments for classes and functions

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +  getFile(path: string) {
Add return type

2023-04-12 09:25 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk.ts
> +  const getAt = (offset: number) => {
nested function is not good code quality

2023-04-14 21:33 UTC, dariaterekhovaae commented on modules/i3s/src/i3s-loader.ts
> +    data = parseSlpk(data, options, context);
We can use it in 'raw' mode, I think it's better than creating a bunch of unusable code in the project

2023-04-21 19:02 UTC, belom88 requested changes
I expected `SLPKLoader` inside I3S loaders as slpk is the part of I3S spec

2023-04-21 19:02 UTC, belom88 commented on modules/i3s/test/i3s-loader.spec.js
> -test('I3SLoader#slpk is not supported', async (t) => {
Why have you removed this test? slpk is still unsupported by I3SLoader

2023-04-26 15:00 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/index.ts
> +const getByteAt = (offset: number, buffer: DataView) => {
TSDoc comments

2023-04-26 15:07 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/index.ts
> +    if (searchWindow.toString().includes('80,75,1,2')) {
I don't like serialisation. It could diminish performance.
'80,75,1,2' - add some comment for this magic sequence with link to the spec

2023-04-26 15:10 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/index.ts
> +  return await new SlpkArchieve(data, hashFile).getFile(options.path ?? '');
```suggestion
  return await new SlpkArchive(data, hashFile).getFile(options.path ?? '');
```

2023-04-26 15:10 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/index.ts
> +  const slpkArchieve = new DataView(data);
```suggestion
  const slpkArchive = new DataView(data);
```

2023-04-26 15:11 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/local-file-header.ts
> +export default class LocalFileHeader {
TSDoc comments

2023-04-26 15:12 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/local-file-header.ts
> +  getFileNameLength() {
Ditto regarding getters

2023-04-26 15:15 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/local-file-header.ts
> +  }
Ditto regarding parameter properties in constructor

2023-04-26 15:16 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +export default class SlpkArchieve {
TSDoc comments

2023-04-26 15:18 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +    }
Avoid difficult logic in the constructor. Make `private initializeHashArray` method

2023-04-26 15:19 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/cd-file-header.ts
> +  cdCompressedSize = 20;
private/public modifiers are nice to use in classes

2023-04-26 15:20 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/local-file-header.ts
> +  fileName = 30;
Ditto regarding some `Record<string, number>` for offsets

2023-04-26 15:21 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +  async getFile(path: string, mode: 'http' | 'raw' = 'raw') {
Add return types throughout the PR

2023-04-26 15:23 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +    const decompressedData = await processOnWorker(CompressionWorker, compressedFile, {
not all files inside slpk are gzip compressed (see I3S spec https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#scene-layer-packages-)

2023-04-26 15:25 UTC, belom88 commented on modules/i3s/test/parse-slpk.spec.js
> +test('SlpkLoader#local file header parce', async (t) => {
make individual files to test these classes `test/parsers/parse-slpk/cd-file-header.spec.js`, `test/parsers/parse-slpk/local-file-header.spec.js`

2023-04-28 17:30 UTC, dariaterekhovaae commented on modules/i3s/src/lib/parsers/parse-slpk/cd-file-header.ts
> +  }
Since babel doesn't handle constructor assignment correct, we decided not to change it

2023-05-04 11:59 UTC, ibgreen approved these changes

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/i3s-slpk-loader.ts
> +import {parseSlpk} from './lib/parsers/parse-slpk';
- I would prefer keeping this capitalized `parseSLPK`, `SLPKLoader`, `SLPKLoaderOptions` ...

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/i3s-slpk-loader.ts
> +  module: 'slpk',
module should be `i3s` - I believe it is used to construct worker paths. Even if you don't have a worker loader let's keep it correct.

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/i3s-slpk-loader.ts
> +  name: 'I3S (Indexed Scene Layers)',
```suggestion
  name: 'I3S SLPK (Scene Layer Package)',
```

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-slpk/cd-file-header.ts
> + * Class for handling central directory file header of zip file
Is this a zip file parser? Let's put it in a separate directory and have names include `zip`

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-slpk/index.ts
> +import {SlpkLoaderOptions} from 'modules/i3s/src/i3s-slpk-loader';
In loaders.gl we never use `index.ts` files inside modules. when dealing with a lot of files, the extra nesting confuses more than it helps.

Rename this file to `parse-slpk.ts`?

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-slpk/local-file-header.ts
> +export default class LocalFileHeader {
Nit: I recommend not using `export default`, prefer named exports

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +  slpkArchive: DataView;
+1 Naturally we don't capitalize here, just in types and function names.

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
> +  private parseHashFile(hashFile: ArrayBuffer): HashElement[] {
Please add a JSDoc line `/** */` in front of every class type and function.

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/test/data/test.zip.js
> +export const DATA_ARRAY = new Uint8Array([
Add comment explaining what this contains.

2023-05-04 11:59 UTC, ibgreen commented on modules/i3s/test/local-file-header.spec.js
> +  const localFileHeader = new LocalFileHeader(0, new DataView(DATA_ARRAY.buffer));
```suggestion
  const localFileHeader = parseZipHeader(0, new DataView(DATA_ARRAY.buffer));
```

2023-05-04 22:31 UTC, merged