(feat(tile-converter): support attributes data from textures
visgl/loaders.gl pull request #2515
Opened 2023-06-09 22:39 UTC by dariaterekhovaae

2023-06-12 07:29 UTC, belom88 requested changes
* The PR title must be changed;
* I don't agree with naming: "slpk converter". SLPK is part of I3S so "Convert SLPK to I3S" doesn't have sense. I'd prefer "Extract SLPK" and following changes for file names, function names etc.

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +  file: DataView;
Probably, make it private

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * Gets an unsigned 16-bit integer (unsigned byte) at the specified byte offset from the start of the file.
```suggestion
   * Gets an unsigned 16-bit integer at the specified byte offset from the start of the file.
```
16-bit is not byte. Well known name is "short"

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * Gets an unsigned 32-bit integer (unsigned byte) at the specified byte offset from the start of the file.
```suggestion
   * Gets an unsigned 32-bit integer at the specified byte offset from the start of the file.
```
32-bit are 4 bytes

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param offset The offset, in byte, from the start of the file where to read the data.
```suggestion
   * @param offset The offset, in bytes, from the start of the file where to read the data.
```

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param offset The offset, in byte, from the start of the file where to read the data.
```suggestion
   * @param offset The offset, in bytes, from the start of the file where to read the data.
```

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param offset The offset, in byte, from the start of the file where to read the data.
```suggestion
   * @param offset The offset, in bytes, from the start of the file where to read the data.
```

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param startOffsset The offset, in byte, from the start of the file where to start reading the data.
```suggestion
   * @param startOffsset The offset, in bytes, from the start of the file where to start reading the data.
```

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param endOffset The offset, in byte, from the start of the file where to end reading the data.
```suggestion
   * @param endOffset The offset, in bytes, from the start of the file where to end reading the data.
```

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/file-provider.ts
> +   * @param endOffset The offset, in byte, from the start of the file where to end reading the data.
Ditto for comments misprints

2023-06-12 07:29 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/local-file-header.ts
> +   */
```suggestion
  /** File name */
```
More compact form

2023-06-12 07:29 UTC, belom88 commented on modules/tile-converter/src/slpk-converter/slpk-converter.ts
> +  options: any;
Add better type for options

2023-06-26 15:25 UTC, dariaterekhovaae commented on modules/tile-converter/src/slpk-converter/slpk-converter.ts
> +        _workerType: 'test',
What worker type should I use? Or where can I find any info about them?

2023-07-03 10:46 UTC, belom88 requested changes
Hidden comments from previous review are not fixed

2023-07-03 10:46 UTC, belom88 commented on modules/tile-converter/src/slpk-converter-cli.ts
>  // import {join} from 'path';
remove "converter" from naming (file names and variables)

2023-07-03 10:46 UTC, belom88 commented on modules/tile-converter/src/slpk-converter/slpk-converter.ts
> +    await writeFile(dirName, options.data, fileName);
Can we do it without `path` usage:
```suggestion
    await writeFile(outputPath, options.data, options.name);
```

2023-07-03 12:24 UTC, dariaterekhovaae commented on modules/i3s/src/lib/parsers/parse-zip/local-file-header.ts
> +  if (Buffer.from(await buffer.slice(headerOffset, headerOffset + 4)).compare(signature) !== 0) {
This behavior is tested during the slpk loader browser test

2023-07-03 14:38 UTC, belom88 requested changes

2023-07-03 14:38 UTC, belom88 commented on modules/tile-converter/test/slpk-converter/slpk-converter.spec.js
> +test('tile-converter - searchFromTheEnd', async (t) => {
Could you rename this test as I done unified naming: https://github.com/visgl/loaders.gl/pull/2533/files.
Start from "tile-converter(slpk-extractor)#......"

2023-07-04 09:04 UTC, belom88 approved these changes
Some extra comments nice to have

2023-07-04 10:27 UTC, ibgreen approved these changes
The FileProvider overlaps some other similar code in loader-utils. 

We don't need to align now, but we may want to come back to it.

When working in the browser you'd benefit from BlobProvider. Blobs allow you to read partial files so that you can work with very large files, perfect for SLPKs.

2023-07-04 10:27 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +export class BufferFileProvider implements FileProvider {
If this provides a file using DataView, why is it not called `DataViewFileProvider`? `BufferFileProvider` seems to suggest the Node.js `Buffer` class.

2023-07-04 10:27 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +  slice(startOffsset: number, endOffset: number): Promise<ArrayBuffer> {
```suggestion
  slice(startOffset: number, endOffset: number): Promise<ArrayBuffer> {
```

2023-07-04 10:27 UTC, ibgreen commented on modules/i3s/src/lib/parsers/parse-zip/buffer-file-provider.ts
> +   * @param startOffsset The offset, in bytes, from the start of the file where to start reading the data.
```suggestion
   * @param startOffset The offset, in bytes, from the start of the file where to start reading the data.
```

2023-07-04 15:28 UTC, merged