chore(tile-converter): Support of SLPKs larger then 2 Gb
visgl/loaders.gl pull request #2547
Opened 2023-07-12 11:58 UTC by dariaterekhovaae

2023-07-13 15:21 UTC, belom88 requested changes

2023-07-13 20:02 UTC, ibgreen approved these changes

2023-07-19 07:51 UTC, belom88 approved these changes

2023-07-19 07:51 UTC, belom88 commented on modules/i3s/test/zip-utils/data-view-provider.spec.js
> +import test from 'tape-promise/tape';
FYI: It is possible to make *.ts tests

2023-07-19 07:51 UTC, belom88 commented on modules/i3s/src/lib/parsers/parse-zip/signature.ts
> +export type ZipSignature = [number, number, number, number];
Nit. The type is so simple. The better is just declare a variable with this tuple:
```
const zipSignature: [number, number, number, number] = [1,2,3,4];
```
The separate file is too much for it.

2023-07-20 13:58 UTC, merged