fix(tile-converter): fix loading buffers in preprocess-3d-tiles
visgl/loaders.gl pull request #2572
Opened 2023-08-03 06:38 UTC by mspivak-actionengine

2023-08-03 16:12 UTC, ibgreen approved these changes

2023-08-04 09:40 UTC, belom88 requested changes
This change doesn't fix the problem in `gltf`. The problem is that `KHR_texture_transform` extension fails if buffers are not loaded.
I suggest making a change in https://github.com/visgl/loaders.gl/blob/f51905b1385c8ba51c238adc70868fed997474fa/modules/gltf/src/lib/extensions/KHR_texture_transform.ts#L64
```
if (!hasExtension || !options.gltf?.loadBuffers) {
```
A test case in `modules/gltf/test/lib/extensions/KHR_texture_transform.spec.js` will be appreciated.

2023-08-11 09:44 UTC, belom88 commented on modules/gltf/src/lib/api/post-process-gltf.ts
> +      const jsonPost: GLTFPostprocessed = {...json};
It doesn't return postprocessed gltf that is anoying for a user. I don't agree with this change

2023-08-11 09:46 UTC, belom88 commented on modules/gltf/test/lib/extensions/KHR_texture_transform.spec.js
> +   */
Convert the file to TypeScript probably

2023-08-11 09:48 UTC, belom88 commented on modules/gltf/test/lib/extensions/KHR_texture_transform.spec.js
> +  const gltf = postProcessGLTF(gltfWithBuffers, loaderOptions);
We don't do postprocess gltf without buffer usually

2023-08-11 13:26 UTC, belom88 approved these changes

2023-08-11 14:24 UTC, merged