feat(3d-tiles): some improvements
visgl/loaders.gl pull request #2610
Opened 2023-08-30 14:29 UTC by dariaterekhovaae

Fix for review comments from https://github.com/visgl/loaders.gl/pull/2578

2023-08-30 15:02 UTC, ibgreen approved these changes

2023-08-30 15:02 UTC, ibgreen commented on modules/3d-tiles/src/tz3-loader.ts
> +async function parse3tz(
`parse3DTilesArchive`

2023-08-31 07:30 UTC, belom88 requested changes

2023-08-31 07:30 UTC, belom88 commented on modules/3d-tiles/src/index.ts
> +export type {Tiles3DArchiveFileLoaderOptions} from './tz3-loader';
rename files and folders: `tz3**` -> `3d-tiles-archive**`. We can start file name from a number

2023-08-31 07:30 UTC, belom88 commented on modules/3d-tiles/src/tz3/tz3-archive.ts
> +   * @param zipArchiveFile - FileProvider with whe whole file
```suggestion
   * @param zipArchiveFile - FileProvider with the whole file
```

2023-08-31 07:30 UTC, belom88 commented on modules/3d-tiles/src/tz3/tz3-archive.ts
> +    return decompressedFile.buffer;
`this.getFileBytes` returns `ArrayBuffer`. If you want to handle `null`, it is a weird way. I'd recomment `throw` in null case. That means that the file has not been found

2023-08-31 07:30 UTC, belom88 commented on modules/3d-tiles/src/tz3/tz3-archive.ts
> +  private zipArchiveFile: FileProvider;
```suggestion
  private fileProvider: FileProvider;
```

2023-09-01 10:35 UTC, belom88 approved these changes

2023-09-01 12:21 UTC, merged