Chore: Build node workers as ES modules
visgl/loaders.gl pull request #2791
Opened 2023-11-17 19:40 UTC by ibgreen

2023-11-20 10:46 UTC, belom88 commented
This is exactly what I've reverted in https://github.com/visgl/loaders.gl/pull/2790 . We can probably revert `*.cjs` back to `*.js` extensions but `--format=esm` is exactly what is breaking the tile converter right now.
`cjs`/`js` is about what is working in NodeJS by default. https://github.com/visgl/loaders.gl/pull/2775 seem for me a breaking commit.

2023-11-20 10:49 UTC, belom88 commented
The error is "Worker exception: Error: Dynamic require of "stream" is not supported"

2023-11-20 12:20 UTC, ibgreen commented
> The error is "Worker exception: Error: Dynamic require of "stream" is not supported"

Can you pintpoint the line where this is happening. Since I can't find it in the source code I am assuming it is happening in the built code. But if we are building with --format=esm, seems that require shouldn't be emitted, so it is a mystery error?

2023-11-20 12:29 UTC, belom88 commented
> > The error is "Worker exception: Error: Dynamic require of "stream" is not supported"
> 
> Can you pintpoint the line where this is happening? Since I can't find it in the source code I am assuming it is happening in the built code. But if we are building with --format=esm, seems that require shouldn't be emitted, so it is a mystery error?

Probably, the root cause is in decoder/encoder libs (`modules/draco/src/libs/draco_encoder.js`, `modules/draco/src/libs/draco_wasm_wrapper.js`)

2023-11-20 12:31 UTC, belom88 requested changes
The tile converter fails with "Worker exception: Error: Dynamic require of "stream" is not supported". Probably draco encoder/decoder libs a not compatible with esm.

2023-11-20 12:44 UTC, ibgreen commented
> Probably draco encoder/decoder libs a not compatible with esm. 

Yes that could be. I suppose if they were renamed to .cjs it might work. I guess in that case we'd need to copy them from the Google CDN.

2024-03-28 13:17 UTC, ibgreen commented
@belom88 Can you take another look at this now that it is rebased on the new build system. Do your concerns still apply?

2026-07-31 13:21 UTC, closed without merging