fix(tile-converter): skip showing progress with no analyze
visgl/loaders.gl pull request #2875
Opened 2024-01-31 08:52 UTC by mspivak-actionengine

2024-01-31 09:40 UTC, belom88 requested changes

2024-01-31 09:40 UTC, belom88 commented on modules/tile-converter/src/i3s-converter/helpers/progress.ts
> +    if (!this._stepsTotal || !this._stepsDone || !this.startTime) {
Can we add a test for this corner case?

2024-01-31 09:40 UTC, belom88 commented on modules/tile-converter/src/lib/utils/statistic-utills.ts
> +    result += `${Math.floor(milliseconds)}ms`;
Can we add a test for this change?

2024-01-31 12:03 UTC, mspivak-actionengine commented on modules/tile-converter/src/lib/utils/statistic-utills.ts
> +    result += `${Math.floor(milliseconds)}ms`;
Done

2024-02-07 10:56 UTC, belom88 approved these changes

2024-02-07 11:12 UTC, merged