chore(i3s examples): replace i3s example by i3s colorization
visgl/loaders.gl pull request #2887
Opened 2024-02-19 12:55 UTC by maxkuznetsov-actionengine

2024-02-19 14:16 UTC, belom88 requested changes
This is too large for an example.
I'd just have a dropdown with attributes to colorize. We don't need to have histogram, set of icons, picking and so on.
Could we make colorization and i3s removal in different PRs?

2024-02-19 14:58 UTC, dsavinov-actionengine commented
> This is too large for an example. I'd just have a dropdown with attributes to colorize. We don't need to have histogram, set of icons, picking and so on. Could we make colorization and i3s removal in different PRs?

1. For the UI, would you both @maxkuznetsov-actionengine @belom88 agree with this?
![image](https://github.com/visgl/loaders.gl/assets/128065385/996355ed-652e-4aa4-8eb4-f0c043efa86a)

2.  Splitting in 2 different PRs - ok.

2024-02-20 15:00 UTC, belom88 commented
> > This is too large for an example. I'd just have a dropdown with attributes to colorize. We don't need to have histogram, set of icons, picking and so on. Could we make colorization and i3s removal in different PRs?
> 
> 1. For the UI, would you both @maxkuznetsov-actionengine @belom88 agree with this?
>    ![image](https://private-user-images.githubusercontent.com/128065385/305992493-996355ed-652e-4aa4-8eb4-f0c043efa86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA5NDksIm5iZiI6MTcwODQ0MDY0OSwicGF0aCI6Ii8xMjgwNjUzODUvMzA1OTkyNDkzLTk5NjM1NWVkLTY1MmUtNGFhNC04ZWI0LWYwYzA0M2VmYTg2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNDUwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTc2OWY0YzUyZDI5NzhjNjg2ZmQ0YmU3ZWYwOGNiODc4ZGFkM2JkOTM2ZTljYjE3MDY5YWE2YzllMDU0ZmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0IbwJWRdUTAXWa_4O6Y_XjPHi1TT6CBJ59_vES1i14Y)
> 
> For Colorize Mode: None/Replace/Multiply For Colorize Attribute: None/Selected Attribute None is default for both
> 
> 2. Splitting in 2 different PRs - ok.

I suggest swiping controls. User selects from top to down direction. 1st - select attribute, 2nd - select mode (if needed)

2024-02-26 14:51 UTC, ibgreen approved these changes

2024-02-28 08:39 UTC, belom88 approved these changes

2024-02-28 08:39 UTC, belom88 commented on examples/website/i3s-colorization-by-attributes/src/types.ts
> +export type COLOR = [number, number, number, number];
CAPS is for constants

```suggestion
export type Color = [number, number, number, number];
```

2024-02-28 08:39 UTC, belom88 commented on examples/website/i3s-colorization-by-attributes/src/types.ts
> +  minColor: COLOR;
There is a `Color` type in @deck.gl

2024-02-28 10:04 UTC, maxkuznetsov-actionengine commented on examples/website/i3s-colorization-by-attributes/src/types.ts
> +export type COLOR = [number, number, number, number];
Removed type definition

2024-02-28 10:04 UTC, maxkuznetsov-actionengine commented on examples/website/i3s-colorization-by-attributes/src/types.ts
> +  minColor: COLOR;
added import from deck

2024-02-28 10:49 UTC, merged